algoritmo "QuadradoCuboQuartaPot"
//Função: Informa quadrado, cubo e quarta potência do número informado pelo usuário.
//Autora: Caroline Scherer
//Data: 04/10/2019

var

N : Inteiro

inicio

Repita
	Escreva("Informe um número inteiro positivo: ")
	Leia(N)
	EscrevaL("O quadrado do número informado é",N^2,".")
   EscrevaL("O cubo do número informado é",N^3,".")
   EscrevaL("A quarta potência do número informado é",N^4,".")
Ate N = 0

fimalgoritmo
